- name:  Enable Remote Desktop Protocol
  hosts: 172.23.18.140
  gather_facts: false
  tasks:
       
    - name: Run PowerShell command
      win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections 
        data: 0x00000000
        type: dword
        state: present
        
    - name: Set service startup mode to auto and ensure it is started
      win_service:
        name: TermService
        state: started

    - name: Add firewall rule for RDP when remoteip is IPv4 
      win_firewall_rule:
        name: AWXRDPAllow
        enabled: yes
        state: present
        localport: 3389
        remoteip: 192.168.0.55
        action: allow
        direction: in
        protocol: tcp
