---
- name: Gather OS information
  hosts: all
  gather_facts: yes

  tasks:
    - name: Print operating system
      ansible.builtin.debug:
        msg: "Host: {{ inventory_hostname }}, OS: {{ ansible_os_family }} ({{ ansible_distribution }})"
