---
- name: Collect OS info and send report via email
  hosts: all
  gather_facts: yes
  vars:
    email_sender: "ansible@upay.systems"
    email_recipient: "jahangir.alam@upaybd.com"
    email_subject: "System OS Info Report"
    smtp_host: "172.23.18.26"
    smtp_port: 465
    smtp_username: "ansible@upay.systems"
    smtp_password: "Upay@321"

  tasks:

    - name: Collect system info
      set_fact:
        system_report: |
          Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
          IP Address: {{ ansible_default_ipv4.address }}
          Memory: {{ ansible_memtotal_mb }} MB
          Uptime: {{ ansible_uptime_seconds }} seconds

    - name: Save system report to file
      copy:
        content: "{{ system_report }}"
        dest: /tmp/system_report.txt

    - name: Send OS info report via email
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_recipient }}"
        subject: "{{ email_subject }}"
        body: "{{ system_report }}"
        secure: starttls
