---
- name: Generate full OS and kernel version report
  hosts: all
  gather_facts: yes
  tasks:
    - name: Create report line with OS family, name, version, and kernel
      ansible.builtin.set_fact:
        os_report_line: >
          {{ inventory_hostname }},
          {{ ansible_os_family | default('Unknown') }},
          {{ ansible_distribution | default('Unknown') }},
          {{ ansible_distribution_version | default('Unknown') }},
          {{ ansible_kernel | default('Unknown') }}

    - name: Write OS info to local report file
      ansible.builtin.lineinfile:
        path: /tmp/os_report.csv
        line: "{{ os_report_line | regex_replace('\\s+', ' ') }}"
        create: yes
        insertafter: EOF
      delegate_to: localhost
      
- name: Send OS report via email
  hosts: localhost
  become: yes
  tasks:
    - name: Email the OS report
      mail:
        host: 172.23.18.26
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: jahangir.alam@upaybd.com
        subject: "Ansible OS Report"
        body: "Attached is the OS report generated by Ansible."
        attach:
          - /tmp/os_report.csv
        secure: starttls
