- name: Enable Remote Desktop Protocol
  hosts: 172.23.18.140
  gather_facts: false
  tasks:
    
    - name: Run PowerShell command   
      win_regedit:
        path: HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword
        state: present       
        
    - name: Set service startup mode to auto and ensure it is started
      win_service:
        name: TermService
        state: started
      
    - name: Enable RDP Firewall Rule
      win_firewall_rule:
        name: RemoteDesktop-In-TCP
        enable: yes
        state: present
        localport: 33389
        action: allow
        direction: in
        protocol: tcp
