---
  - name: mail send using ansible
    hosts: 127.0.0.1
    connection: local
    tasks:
      - name: mail
         mail:
          host: 172.23.18.26
          port: 465
          usernaem: "ansible@upay.systems"
          password: "Upay@321"
          to: "ansible@upay.systems"
          subjecet: "Sending email from anisble"
