---
- name: Send OS report via email
  hosts: localhost
  tasks:
    - name: Send email with attachment
      mail:
        host: 172.23.18.26
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: jahangir.alam@upaybd.com
        subject: "Ansible OS & Kernel Report"
        body: "Please find the attached OS and Kernel version report."
        attach:
          - ./os_kernel_report.txt
