---
- name: Generate Windows Update Report
  hosts: 172.23.18.12
  gather_facts: false
  tasks:
    - name: Get Windows Update history
      ansible.windows.win_updates:
        state: searched
      register: update_info

    - name: Save update report to a file on controller
      copy:
        content: "{{ update_info }}"
        dest: "/tmp/{{ inventory_hostname }}_windows_update_report.json"
      delegate_to: localhost
